name: "Mo's Mod Life"
favicon: null
layout_spectrum: 0.80203
typography_spectrum: 0.52862
title: "Mo's Mod Life"
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#e4e4e4'
    - '#d42d4b'
    - '#b77249'
    - '#7db19b'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
