title: Rosemary & Gingham
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1875
  brandStrength: 0.8315412
  rhythmicContrast: 0.75
  brandColors:
    - '#F8E2EF'
    - '#38453E'
    - '#B8D0DC'
    - '#467C64'
    - '#85A8A4'
  lightness: 0.75
navigation:
  - name: Food & Drinks
    id: 3fd836f8-f028-4a55-acba-745d12d227fe
    type: content
  - name: Mommy & Baby
    id: 63321bf5-dbc6-42d0-8eeb-f9b978488fa4
    type: content
  - name: Green Living & Homekeeping
    id: f701580a-6044-42d7-b086-6de81f00b98f
    type: content
  - name: 'DIYs, Design & Crafts'
    id: 545384bb-865a-4fe8-93a7-47f3ec79d9f2
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Rosemary & Gingham
opengraph:
  image: null
  type: null
  appId: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/af705300-1d77-4a53-9043-3ff593683dde.jpg
typography_spectrum: 0.07526882
layout_spectrum: 0
