name: "Mo's Mod Life"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52862
title: "Mo's Mod Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6dea4'
    - '#0bbdaf'
    - '#ff0f1d'
    - '#1b0f4a'
    - '#8b859f'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
