layout_spectrum: 0.18168846936896443
typography_spectrum: 0.956250784220174
color:
  brandColors:
    - '#0a0e0f'
    - '#d8293a'
    - '#9cce99'
    - '#ea817d'
    - '#ffffff'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/af705300-1d77-4a53-9043-3ff593683dde.jpg
name: Rosemary & Gingham
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Food & Drinks
    id: 3fd836f8-f028-4a55-acba-745d12d227fe
    type: content
  - name: Mommy & Baby
    id: 63321bf5-dbc6-42d0-8eeb-f9b978488fa4
    type: content
  - name: Green Living & Homekeeping
    id: f701580a-6044-42d7-b086-6de81f00b98f
    type: content
  - name: 'DIYs, Design & Crafts'
    id: 545384bb-865a-4fe8-93a7-47f3ec79d9f2
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Rosemary & Gingham
purpose: []
