layout_spectrum: 1
typography_spectrum: 0.05376344
color:
  saturation: 0.5259385
  lightness: 0.8082455
  brandStrength: 0.65498
  rhythmicContrast: 0.3953308
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: "Mo's Mod Life"
