title: "Mo's Mod Life"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.6415771
  lightness: 0.8125
  brandColors:
    - '#FCE6AA'
    - '#54CCCA'
    - '#398A8D'
    - '#EF1E1C'
    - '#5F160D'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "Mo's Mod Life"
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.52862
layout_spectrum: 1
