name: "Mo's Mod Life"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52862
title: "Mo's Mod Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060000'
    - '#00c1aa'
    - '#f69b83'
    - '#494235'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
