title: "Mo's Mod Life"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6577061
  brandStrength: 0.4551971
  lightness: 0.6290323
  brandColors:
    - '#7D7769'
    - '#F75E4F'
    - '#91C09E'
    - '#EAC761'
    - '#E8DF9C'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: "Mo's Mod Life"
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.52862
layout_spectrum: 1
