name: "Mo's Mod Life"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52862
title: "Mo's Mod Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#aeaeac'
    - '#00cbcc'
    - '#444346'
    - '#af028b'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
