name: "Mo's Mod Life"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52862
title: "Mo's Mod Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fce6aa'
    - '#54ccca'
    - '#ef1d1c'
    - '#398a8d'
    - '#f4a199'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
